baseURL = 'https://pxwxnvermx.in/blog/'
languageCode = 'en-us'
title = 'pxwxnvermx'
theme = 'sencilla'

[taxonomies]
tag = 'tags'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/pxwxnvermx"
